# Generated by Django 4.2.10 on 2024-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chathistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroomid', models.IntegerField()),
                ('history', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainuser', models.IntegerField()),
                ('groupuser', models.CharField(max_length=2000)),
                ('chathistory', models.CharField(max_length=2000)),
            ],
        ),
    ]
