# Generated by Django 4.2.10 on 2024-03-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='detail',
            field=models.CharField(default='nothing', max_length=80),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='roomname',
            field=models.CharField(default='noname', max_length=40),
        ),
    ]
