# Generated by Django 4.2.10 on 2024-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_detail_chatroom_roomname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField()),
                ('groupuserid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='groupuser',
        ),
    ]
